name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when you push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Set the type of machine to run on

    steps:
    - name: Checkout code  # Step to checkout the repository code
      uses: actions/checkout@v2

    - name: Setup Ruby  # Step to set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Ensure this matches the Ruby version you use locally

    - name: Cache Ruby gems  # Step to cache installed gems between runs
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies  # Step to install Ruby gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Build Jekyll site  # Step to build the site using Jekyll
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages  # Step to deploy the site to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        destination_branch: 'gh-pages'  # Branch to push the build outputs

